### ISSUE TITLE
论文3.3节中，初始的关键点特征F={f_i}是怎么计算的？

### ISSUE THREAD

**Issue by Zephyr-One** [RuyiLian/CheckerPose#1]

**Comment by RuyiLian** [comment]
你好，我们在论文中用 $F_G^{(0)}$ 表示初始的关键点特征，计算方式见3.3节第三段（即第四页最后一段）和图2(a)，对应代码为

https://github.com/RuyiLian/CheckerPose/blob/719fee1c353d0e5a650dddbe14cc69c32d73b1c5/checkerpose/model/init.py#L110-L114

**Comment by Zephyr-One** [comment]
> 你好，我们在论文中用 FG(0) 表示初始的关键点特征，计算方式见3.3节第三段（即第四页最后一段）和图2(a)，对应代码为
> 
> https://github.com/RuyiLian/CheckerPose/blob/719fee1c353d0e5a650dddbe14cc69c32d73b1c5/checkerpose/model/init.py#L110-L114

好的，多谢！

**Comment by Zephyr-One** [comment]
自遮挡的关键点b_v值等于0吗？被遮挡的呢？还是说只是截断在RoI外的才是0？
对论文中“For N (N ≫ 8) 3D keypoints P, we first predict whether their 2D projections appear in the RoI I_O, and then localize the keypoints inside I_O, denoted as P_I ."不是很理解，这对理解后续的损失函数也很关键，谢谢指点~
另外，对b_x和b_y的预测值是否也是0~1之间的概率值？还是说是一个0或1的布尔值？

**Comment by RuyiLian** [comment]
1. 只有截断在RoI外的才是0。
2. 基于关键点的方法基本都是使用提前定义好的关键点。在CheckerPose中我们采用物体表面均匀采样的512个关键点（即 $\mathcal{P}$ ），但不是所有关键点都一定在RoI里面。对于截断在RoI外的关键点，我们没法定义 $b_x$, $b_y$ 。又由于我们的关键点足够密集，所以我们即使忽略RoI外部的关键点也有足够的3D-2D correspondences来确定pose。在计算 $b_x$, $b_y$ 的损失函数和求解PnP过程中我们不考虑RoI外的点。
3.  网络输出的 $b_v$, $b_x$, 和 $b_y$ 的预测值都是概率值，我们使用0.5作为分界来得到最终的0/1编码。

---
1. We set  $b_v=0$ for keypoints outside the RoI.  
2. Keypoint-based methods mainly localize predefined keypoints. In CheckerPose, we use 512 keypoints on the object surface (i.e. $\mathcal{P}$). However, some keypoints may not appear in the input RoI, and we can not define $b_x$, $b_y$ for such keypoints. Since our keypoints are much denser than previous works, we still have enough 3D-2D correspondences for solving PnP problem if we just ignore the keypoints outside the RoI. We use $b_v$ to denote whether a keypoint appears in the RoI, and ignore keypoints with $b_v=0$ for loss computation of $b_x$, $b_y$ and PnP process. 
3. The network predictions of $b_v$, $b_x$, and $b_y$ are all probabilities. We get 0/1 binary values using 0.5 as the threshold.

**Comment by Zephyr-One** [comment]
好的好的，非常感谢作者的耐心解答！
